apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: command
  name: command
spec:
  type: NodePort
  ports:
  - name: "48082"
    port: 48082
    targetPort: 48082
  selector:
    io.kompose.service: command
status:
  loadBalancer: {}
