apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: config-seed
  name: config-seed
spec:
  type: NodePort
  ports:
  - name: "8300"
    port: 8300
    targetPort: 8300
  - name: "8400"
    port: 8400
    targetPort: 8400
  - name: "8500"
    port: 8500
    targetPort: 8500
  - name: "8600"
    port: 8600
    targetPort: 8600
  selector:
    io.kompose.service: config-seed
status:
  loadBalancer: {}
