apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: data
  name: data
spec:
  type: NodePort
  ports:
  - name: "48080"
    port: 48080
    targetPort: 48080
  - name: "5563"
    port: 5563
    targetPort: 5563
  selector:
    io.kompose.service: data
status:
  loadBalancer: {}
