apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: device-virtual
  name: device-virtual
spec:
  type: NodePort
  ports:
  - name: "49990"
    port: 49990
    targetPort: 49990
  selector:
    io.kompose.service: device-virtual
status:
  loadBalancer: {}
