apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.12.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: export-distro
  name: export-distro
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: export-distro
    spec:
      containers:
      - env:
        - name: EXPORT_DISTRO_CLIENT_HOST
          value: export-client
        - name: EXPORT_DISTRO_CONSUL_HOST
          value: edgex-config-seed
        - name: EXPORT_DISTRO_DATA_HOST
          value: edgex-core-data
        - name: EXPORT_DISTRO_MQTTS_CERT_FILE
          value: none
        - name: EXPORT_DISTRO_MQTTS_KEY_FILE
          value: none
        image: edgexfoundry/docker-export-distro
        name: edgex-export-distro
        ports:
        - containerPort: 48070
        resources: {}
        volumeMounts:
        - mountPath: /data/db
          name: db-data
        - mountPath: /edgex/logs
          name: log-data
        - mountPath: /consul/config
          name: consul-config
        - mountPath: /consul/data
          name: consul-data
      hostname: edgex-export-distro
      restartPolicy: Always
      volumes:
      - name: db-data
        persistentVolumeClaim:
          claimName: db-data
      - name: log-data
        persistentVolumeClaim:
          claimName: log-data
      - name: consul-config
        persistentVolumeClaim:
          claimName: consul-config
      - name: consul-data
        persistentVolumeClaim:
          claimName: consul-data
status: {}
