apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: logging
  name: logging
spec:
  type: NodePort
  ports:
  - name: "48061"
    port: 48061
    targetPort: 48061
  selector:
    io.kompose.service: logging
status:
  loadBalancer: {}
