apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: metadata
  name: metadata
spec:
  type: NodePort
  ports:
  - name: "48081"
    port: 48081
    targetPort: 48081
  selector:
    io.kompose.service: metadata
status:
  loadBalancer: {}
