apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: rulesengine
  name: rulesengine
spec:
  type: NodePort
  ports:
  - name: "48075"
    port: 48075
    targetPort: 48075
  selector:
    io.kompose.service: rulesengine
status:
  loadBalancer: {}
