apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: scheduler
  name: scheduler
spec:
  type: NodePort
  ports:
  - name: "48085"
    port: 48085
    targetPort: 48085
  selector:
    io.kompose.service: scheduler
status:
  loadBalancer: {}
